version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - ${PROMETHEUS_HOST_PORT}:${PROMETHEUS_CONTAINER_PORT}/tcp
    networks:
      - back_net
      - front_net
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${LATEST_VERSION}
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${LATEST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${LATEST_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
     ipam:
         driver: default
         config:
            - subnet: ${BACK_NET}
  front_net:
     ipam:
        driver: default
        config:
           - subnet: ${FRONT_NET}
